// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.5
// source: base/ugit.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UgitObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Oid   string `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`
	Type_ string `protobuf:"bytes,3,opt,name=type_,json=type,proto3" json:"type_,omitempty"`
}

func (x *UgitObject) Reset() {
	*x = UgitObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_ugit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UgitObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UgitObject) ProtoMessage() {}

func (x *UgitObject) ProtoReflect() protoreflect.Message {
	mi := &file_base_ugit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UgitObject.ProtoReflect.Descriptor instead.
func (*UgitObject) Descriptor() ([]byte, []int) {
	return file_base_ugit_proto_rawDescGZIP(), []int{0}
}

func (x *UgitObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UgitObject) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *UgitObject) GetType_() string {
	if x != nil {
		return x.Type_
	}
	return ""
}

var File_base_ugit_proto protoreflect.FileDescriptor

var file_base_ugit_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x75, 0x67, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x0a, 0x55, 0x67, 0x69, 0x74, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x1e, 0x5a, 0x1c, 0x6a, 0x65, 0x72, 0x72, 0x6f, 0x79, 0x64, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x75, 0x67, 0x69, 0x74, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_ugit_proto_rawDescOnce sync.Once
	file_base_ugit_proto_rawDescData = file_base_ugit_proto_rawDesc
)

func file_base_ugit_proto_rawDescGZIP() []byte {
	file_base_ugit_proto_rawDescOnce.Do(func() {
		file_base_ugit_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_ugit_proto_rawDescData)
	})
	return file_base_ugit_proto_rawDescData
}

var file_base_ugit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_ugit_proto_goTypes = []interface{}{
	(*UgitObject)(nil), // 0: base.UgitObject
}
var file_base_ugit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_ugit_proto_init() }
func file_base_ugit_proto_init() {
	if File_base_ugit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_ugit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UgitObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_ugit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_ugit_proto_goTypes,
		DependencyIndexes: file_base_ugit_proto_depIdxs,
		MessageInfos:      file_base_ugit_proto_msgTypes,
	}.Build()
	File_base_ugit_proto = out.File
	file_base_ugit_proto_rawDesc = nil
	file_base_ugit_proto_goTypes = nil
	file_base_ugit_proto_depIdxs = nil
}
